env:
  browser: true
  commonjs: true
  es6: true
  mocha: true
  jquery: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 6
  sourceType: module
rules:
  indent:
    - error
    - tab
  linebreak-style: 0
  quotes:
    - error
    - double
  semi:
    - error
    - always
  no-console: 0