version: '3.7'

services:
    tests:
        container_name: tests
        depends_on: 
        - selenium-hub
        - chrome
        links:
        - chrome
        - selenium-hub
        build:
            context: ./
            dockerfile: ./Dockerfile
        image: test
        network_mode: bridge
        ports:
        - '5300:5300'


    selenium-hub:
        image: selenium/hub
        container_name: selenium-hub
        network_mode: bridge
        environment:
        - GRID_MAX_SESSION=3
        - GRID_BROWSER_TIMEOUT=900000
        - BROWSER_TIMEOUT=900000
        ports:
        - 4444:4444


    chrome:
        image: selenium/node-chrome-debug
        container_name: chrome
        depends_on:
        - selenium-hub
        links:
        - selenium-hub:hub
        network_mode: bridge
        ports: 
        - 5900:5900


